resolver: lts-9.0
packages:
- '.'
- location:
    git: https://github.com/haskell-haskey/haskey
    commit: 0b8d77e
  extra-dep: true
extra-deps:
- haskey-btree-0.1.0.0
- xxhash-ffi-0.1.0.1
- lz4-0.2.3.1
- haskey-btree-0.1.0.0
- numerals-0.4.1
flags: {}
extra-package-dbs: []
